daxctl: replace basename() usage with new path_basename()
A user reports that ndctl fails to compile on MUSL systems:

daxctl/device.c: In function 'parse_device_options':
daxctl/device.c:377:26: error: implicit declaration of function 'basename' [-Wimplicit-function-declaration]
  377 |                 device = basename(argv[0]);
      |                          ^~~~~~~~

There are two versions of basename() with different behaviors:
	GNU basename() from <string.h>: doesn't modify its argument
	POSIX basename() from <libgen.h>: may modify its argument

glibc provides both versions, while MUSL libc only provides the POSIX
version. Previous code relied on the GNU extension without a header
or used the POSIX version inconsistently.

Introduce a new helper path_basename() that returns the portion of a
path after the last '/', the full string if no '/' is present, and a
trailing '/' returns an empty string. This avoids libc-specific
basename() behavior and is safe for argv style and arbitrary paths.

Closes: https://github.com/pmem/ndctl/issues/283
Reviewed-by: Marc Herbert <marc.herbert@linux.intel.com>
Link: https://lore.kernel.org/r/20260116043056.542346-1-alison.schofield@intel.com
Signed-off-by: Alison Schofield <alison.schofield@intel.com>